### ISSUE TITLE
Imagenes para el tutorial.

### ISSUE THREAD

**Issue by ladanez** [souliss/souliss.github.io#12]
![imagen_1](https://cloud.githubusercontent.com/assets/1657291/10479575/771d1d1c-7265-11e5-8441-129dbc6367a1.png)
![imagen_2](https://cloud.githubusercontent.com/assets/1657291/10479574/771b3682-7265-11e5-8a71-d467e90ec748.png)
![imagen_3](https://cloud.githubusercontent.com/assets/1657291/10479576/771e9b60-7265-11e5-80ce-bd1e0feac4f2.jpg)
![imagen_4](https://cloud.githubusercontent.com/assets/1657291/10479572/771a42b8-7265-11e5-8d97-d36f9ae27d28.png)
![imagen_5](https://cloud.githubusercontent.com/assets/1657291/10479573/771a5e06-7265-11e5-9db8-f3130107c028.png)
![imagen_6](https://cloud.githubusercontent.com/assets/1657291/10479582/77419a66-7265-11e5-8dfa-a11d0e420f7c.png)
![imagen_7](https://cloud.githubusercontent.com/assets/1657291/10479578/772fde5c-7265-11e5-9516-2be3017451b5.png)
![imagen_8](https://cloud.githubusercontent.com/assets/1657291/10479577/772f4dfc-7265-11e5-9417-be0ae07506b5.png)
![imagen_9](https://cloud.githubusercontent.com/assets/1657291/10479580/773229aa-7265-11e5-8a57-f0fccc42aa95.png)
![imagen_10](https://cloud.githubusercontent.com/assets/1657291/10479579/7730d474-7265-11e5-9a86-fc3600694717.jpg)
![imagen_11](https://cloud.githubusercontent.com/assets/1657291/10479581/7735df82-7265-11e5-9b79-b1f3b115aaf1.jpg)
![imagen_12](https://cloud.githubusercontent.com/assets/1657291/10479584/7746633e-7265-11e5-98ae-8722fc8b4683.png)
![imagen_13](https://cloud.githubusercontent.com/assets/1657291/10479583/774323ae-7265-11e5-9392-d83af6ddbd7c.png)
![imagen_14](https://cloud.githubusercontent.com/assets/1657291/10479585/77476108-7265-11e5-8853-77cd13b9cd28.png)
![imagen_15](https://cloud.githubusercontent.com/assets/1657291/10479587/7750a394-7265-11e5-8796-82af22bbe9e7.png)
![imagen_16](https://cloud.githubusercontent.com/assets/1657291/10479586/774c2d00-7265-11e5-94de-82dc1579e05e.jpg)
![imagen_17](https://cloud.githubusercontent.com/assets/1657291/10479588/7755c6c6-7265-11e5-91a9-9174dcd9b29a.jpg)
![imagen_18](https://cloud.githubusercontent.com/assets/1657291/10479590/775a6140-7265-11e5-8767-784373ebe2fa.jpg)
![imagen_19](https://cloud.githubusercontent.com/assets/1657291/10479589/775a3ddc-7265-11e5-8448-8f35fb812b82.jpg)
![imagen_19b](https://cloud.githubusercontent.com/assets/1657291/10479591/775ad97c-7265-11e5-95f5-5e969796a9a6.png)
![imagen_20](https://cloud.githubusercontent.com/assets/1657291/10479592/77626764-7265-11e5-9920-a1f5fd044753.jpg)
![imagen_21](https://cloud.githubusercontent.com/assets/1657291/10479593/776888c4-7265-11e5-8638-ba2c63e32c6a.jpg)
![imagen_22](https://cloud.githubusercontent.com/assets/1657291/10479594/776c510c-7265-11e5-91c3-f71d1e36ac1b.jpg)
![imagen_23](https://cloud.githubusercontent.com/assets/1657291/10479596/77709e24-7265-11e5-8ae7-dd57524a1d9c.jpg)
![imagen_24 png](https://cloud.githubusercontent.com/assets/1657291/10479595/776e4d40-7265-11e5-8b45-a6e162890521.jpg)
![imagen_25](https://cloud.githubusercontent.com/assets/1657291/10479597/77738b70-7265-11e5-941c-d15c7edbbe6b.png)

**Comment by plinioseniore** [comment]
@ladanez I'm happy that you are willing to contribute, but you should follow the procedure in the [README](https://github.com/souliss/souliss.github.io/blob/master/README.md)

You don't need to submit the issue, once dropped the image in the issue form you get a link that you can use in your post or tutorial. The images resolution shall match the requirement of the README and you should not use images from third parties as long as those are shared with reproduction rights.

Thanks.

**Comment by ladanez** [comment]
![imagen_2b](https://cloud.githubusercontent.com/assets/1657291/10479875/1b73520e-7267-11e5-8e8d-d77420907190.png)

**Comment by ladanez** [comment]
![imagen_18](https://cloud.githubusercontent.com/assets/1657291/10479980/bdb1e008-7267-11e5-8257-72929fd5070d.jpg)

**Comment by ladanez** [comment]
![imagen_20](https://cloud.githubusercontent.com/assets/1657291/10479990/e23becc0-7267-11e5-859a-db0f879b1399.jpg)

**Comment by ladanez** [comment]
Hello Dario.

I will review again the images to veriry that it has not copyright.

Thanks.
Regards.

2015-10-14 11:25 GMT+02:00 Dario Di Maio <notifications@github.com>:

> @ladanez <https://github.com/ladanez> I'm happy that you are willing to
> contribute, but you should follow the procedure in the README
> <https://github.com/souliss/souliss.github.io/blob/master/README.md>
>
> You don't need to submit the issue, once dropped the image in the issue
> form you get a link that you can use in your post or tutorial. The images
> resolution shall match the requirement of the README and you should not use
> images from third parties as long as those are shared with reproduction
> rights.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/souliss/souliss.github.io/issues/12#issuecomment-147988245>
> .
>



-- 
Ganate el respeto de los demás teniendo la osadía de ser tu mismo.

Skype user: lucky_luck_1978

**Comment by ladanez** [comment]
Hello again Dario.

I´m sorry to create an issue and submit the image, the next time i will do
better :-D

I hope that the manual in english it is useful to the comunity.

Thanks
Regards.

2015-10-14 15:14 GMT+02:00 Luis Adanez <ladanez@gmail.com>:

> Hello Dario.
>
> I will review again the images to veriry that it has not copyright.
>
> Thanks.
> Regards.
>
> 2015-10-14 11:25 GMT+02:00 Dario Di Maio <notifications@github.com>:
>
>> @ladanez <https://github.com/ladanez> I'm happy that you are willing to
>> contribute, but you should follow the procedure in the README
>> <https://github.com/souliss/souliss.github.io/blob/master/README.md>
>>
>> You don't need to submit the issue, once dropped the image in the issue
>> form you get a link that you can use in your post or tutorial. The images
>> resolution shall match the requirement of the README and you should not use
>> images from third parties as long as those are shared with reproduction
>> rights.
>>
>> Thanks.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/souliss/souliss.github.io/issues/12#issuecomment-147988245>
>> .
>>
>
>
>
> --
> Ganate el respeto de los demás teniendo la osadía de ser tu mismo.
>
> Skype user: lucky_luck_1978
>



-- 
Ganate el respeto de los demás teniendo la osadía de ser tu mismo.

Skype user: lucky_luck_1978

**Comment by shineangelic** [comment]
thank you Louis. If you try SoulissApp 1.6.0 I think you'll like it, as I
optimized big layouts (from 7" tablets on)

here's the link, the new version will be published monday on Play store:
https://drive.google.com/open?id=0B-pzmp8AqC8JSTdtZlJ6c1RwWTQ

Alessandro

2015-10-16 8:43 GMT+02:00 Luis Adánez Mateos <notifications@github.com>:
